### ISSUE TITLE
Pregunta

### ISSUE THREAD

**Issue by tomasfiestas** [pdepjm/2023-tp0-presentacion-Agustoledo10#1]
Que copado lo de Notion, pudiste configurarlo bien? yo estuve un tiempo y fue medio quilombo jjajajajaj

**Comment by Agustoledo10** [comment]
Holaa como andas?? Siii me tomo su tiempo igual agarrarle la mano con todas las herramientas  y templates que tiene, pero con unos tutoriales de youtube vas sacando lo basico y de a poquito va quedando :))
