### ISSUE TITLE
MHA

### ISSUE THREAD

**Issue by ZoeDominguez** [pdepjm/2023-tp0-presentacion-Agustoledo10#2]
¿Cuál es tu héroe o villano favorito del anime?

**Comment by Agustoledo10** [comment]
Holaa como andas? Te digo los dos jajaj
*Heroe:* Lemillion (banco una banda su dedicacion y buen corazon) 
*Villano:* Dabi **SPOILER** (le sale re bien poner a los heroes como malos y poner a toda la gente en panico y tiene buena construccion de personajee) los tuyos??
