### ISSUE TITLE
teen wolf

### ISSUE THREAD

**Issue by victoriasolyedid** [pdepjm/2023-tp0-presentacion-Agustoledo10#3]
Buenas Agus!! Cuál es tu personaje fav de teen wolf y por qué? Yo banco a Stiles toda la vida

**Comment by Agustoledo10** [comment]
Hola vickiii, sii stiles toda la VIDAA, peeeeroo faneo una banda al Dereksito Hale, un re personaje ese. Lo re banco x la historia que tuvo y como supo salir de ahi aunque le quedaron los ojos azules :(, pero un cra el derek.
