### ISSUE TITLE
Notion

### ISSUE THREAD

**Issue by frannmv** [pdepjm/2023-tp0-presentacion-Agustoledo10#4]
Seguramente ya lo conoces, pero te recomiendo a Thomas Frank para saber todo de Notion !

**Comment by Agustoledo10** [comment]
Como andas?  no lo tenia al Thomas  jaja, mas que nada uso lo de Easlo, Mr Notion y con un template que subio Cajun Koi Academy organice todo de la facu! Gracias por la dataa
